### ISSUE TITLE
Electronic badge sponsor

### ISSUE THREAD

**Issue by ajs-xmr** [MoneroKon/meta#23]

**Comment by michaesc** [comment]
This work item will probably be managed outside of any Monerokon programs. If we (staff) choose to use electronic badges, they would be donated by a third party and staff would receive regular reports on development and production.

**Comment by michaesc** [comment]
Because access control may be limited by distribution of wristbands, it's important to remember that badges and lanyards (electronic or paper) are optional and can be totally cancelled.

The only reasons to distribute badges (if we do not use them for access control) are:

- Hacker heritage and enthusiasm
- Identification outside the venue
- On site applications via radio
- Hackathons via USB or serial

Our current plans make electronic badges available at no charge, without affecting the event budget.
